export default defineAppConfig({
    site: {
        title: "Punto Damar P.",
        tagline: "Fullstack Engineer",
        logo: {
            nuxt: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Nuxt_logo.svg/330px-Nuxt_logo.svg.png",
            golang: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Go_Logo_Blue.svg/330px-Go_Logo_Blue.svg.png",
            tailwind: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Tailwind_CSS_Logo.svg/330px-Tailwind_CSS_Logo.svg.png",
            vue: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Vue.js_Logo_2.svg/330px-Vue.js_Logo_2.svg.png",
            rails: "https://upload.wikimedia.org/wikipedia/commons/1/16/Ruby_on_Rails-logo.png",
            typescript: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Typescript_logo_2020.svg/250px-Typescript_logo_2020.svg.png",
            react: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/330px-React-icon.svg.png",
            sidekiq: "https://sidekiq.org/assets/sidekiq.png",
            ruby: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Ruby_logo.png/250px-Ruby_logo.png",
            mongodb: "https://mongodb-js.github.io/leaf/mongodb-leaf_128x128.png",
            postgresql: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Postgresql_elephant.svg/250px-Postgresql_elephant.svg.png",
            firebase: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Firebase_icon.svg/240px-Firebase_icon.svg.png",
            minio: "https://awsmp-logos.s3.amazonaws.com/c6cbc20d-0d79-4256-bbd1-dbb8d219945b/8433cadab9c1c3920e06e695055fb019.png",
            awss3: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Amazon-S3-Logo.svg/250px-Amazon-S3-Logo.svg.png",
            googleStorage: "https://upload.wikimedia.org/wikipedia/commons/d/df/Google_Cloud_storage.svg",
            kafka: "https://upload.wikimedia.org/wikipedia/commons/archive/0/01/20190402143626%21Apache_Kafka_logo.svg",
            docker: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Docker_%28container_engine%29_logo_%28cropped%29.png",
            jenkins: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Jenkins_logo.svg/174px-Jenkins_logo.svg.png",
            privy: "https://avatars.githubusercontent.com/u/65682198?s=200&v=4",
            technopartner: "/technopartner.png",
            laravel: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Laravel.svg",
            jquery: "https://icon.icepanel.io/Technology/svg/jQuery.svg",
            mysql: "https://upload.wikimedia.org/wikipedia/commons/archive/5/51/20220908220043%21Mysql.svg",
            bootstrap: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Bootstrap_logo.svg/330px-Bootstrap_logo.svg.png",
            github: "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png",
            linkedin: "https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg",
            gamelan: "/gamelan.png",
            bikingame: "/bikingame.png",
            unity: "/unity.png",
            construct: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Construct_3_Logo.svg/250px-Construct_3_Logo.svg.png",
            csharp: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Logo_C_sharp.svg/250px-Logo_C_sharp.svg.png",
            smashsports: "/smashsports.png",
            inertia: "https://inertiajs.com/favicon.ico",
            pinia: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Pinialogo.svg/250px-Pinialogo.svg.png",
            websocket: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/WebSocket_colored_logo.svg/250px-WebSocket_colored_logo.svg.png",
            madeindonesia:"/madeindonesia.jpeg",
            alpine: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Alpinejs.png",
            livewire: "https://www.iocod.com/section/stack/Livewire.webp",
            swiper: "https://swiperjs.com/images/swiper-logo.svg",
            figma: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Figma-logo.svg/250px-Figma-logo.svg.png"

        }
    }
});

